def on_overlap_tile(sprite, location):
    # Borra el hongo en la ubicación exacta que tocaste
    tiles.set_tile_at(location, assets.tile("""transparency16"""))
    # Te suma 1 punto al marcador de monedas
    info.change_score_by(1)

scene.on_overlap_tile(SpriteKind.player,
    assets.tile("""miMosaico15"""),
    on_overlap_tile)

def on_overlap_tile2(sprite2, location2):
    game.game_over(False)
    game.set_game_over_effect(False, effects.melt)

scene.on_overlap_tile(SpriteKind.player,
    sprites.builtin.forest_tiles0,
    on_overlap_tile2)

def on_a_pressed():
    if pibble_13.vy == 0:
        pibble_13.vy = -150
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

pibble_13: Sprite = None
scene.set_background_color(9)
pibble_13 = sprites.create(img("""
        ..............................
        ..............................
        ..............3...............
        .........ffff323..............
        ........fddddf3...............
        .......fddddddf...............
        .....ffdffddffdff.............
        ....fdddf1dd1fdddf............
        .....ffddd33dddff.............
        ......fdfdffdfdf..............
        .....fdddfddfdddf.............
        ....fddddddddddddf............
        ...fddfdfd22dfdfddf...........
        ...fdddfd2332dfdddf...........
        ....fdddd2332ddddf............
        .....fdddd22ddddf.............
        ......ffddddddff..............
        .......fddffddf...............
        .......fff..fff...............
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        """),
    SpriteKind.player)
controller.move_sprite(pibble_13, 100, 0)
tiles.set_current_tilemap(tilemap("""
    nivel3
    """))
pibble_13.ay = 200
scene.camera_follow_sprite(pibble_13)