scene.onOverlapTile(SpriteKind.Player, assets.tile`miMosaico15`, function (sprite, location) {
    // Borra el hongo en la ubicación exacta que tocaste
    tiles.setTileAt(location, assets.tile`transparency16`)
    // Te suma 1 punto al marcador de monedas
    info.changeScoreBy(1)
})
scene.onOverlapTile(SpriteKind.Player, sprites.builtin.forestTiles0, function (sprite2, location2) {
    game.gameOver(false)
    game.setGameOverEffect(false, effects.melt)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (pibble_13.vy == 0) {
        pibble_13.vy = -150
    }
})
let pibble_13: Sprite = null
scene.setBackgroundColor(9)
pibble_13 = sprites.create(img`
    ..............................
    ..............................
    ..............3...............
    .........ffff323..............
    ........fddddf3...............
    .......fddddddf...............
    .....ffdffddffdff.............
    ....fdddf1dd1fdddf............
    .....ffddd33dddff.............
    ......fdfdffdfdf..............
    .....fdddfddfdddf.............
    ....fddddddddddddf............
    ...fddfdfd22dfdfddf...........
    ...fdddfd2332dfdddf...........
    ....fdddd2332ddddf............
    .....fdddd22ddddf.............
    ......ffddddddff..............
    .......fddffddf...............
    .......fff..fff...............
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    ..............................
    `, SpriteKind.Player)
controller.moveSprite(pibble_13, 100, 0)
tiles.setCurrentTilemap(tilemap`nivel3`)
pibble_13.ay = 200
scene.cameraFollowSprite(pibble_13)
